package:
  name: spsim
  version: '1.1.dev'

source:
  git_tag: master
  git_url: https://github.com/FXIhub/spsim.git

requirements:
  host:
    - cmake
    - python
    - setuptools
    - swig
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - libspimage 
    - nfft

  run:
    - python
    - hdf5
    - fftw
    - gsl
    - zlib
    - numpy
    - libspimage 
    - nfft

test:
  imports:
    - spsim

about:
  home: https://github.com/FXIhub/spsim
  license: GPL
  license_file: Copyright
  summary: X-ray single particle diffraction simulator

extra:
  recipe-maintainers: 'FilipeMaia'
